title: Incidence
url: "https://patrimoine-photos.github.io"
baseurl: "/Incidence" # Mettre "" si vous utilisez un domaine custom racine.
plugins:
  - jekyll-sitemap
permalink: /articles/:title.html
markdown: kramdown
