backend:
  name: github
  repo: OWNER/REPO # A RENSEIGNER (ex: bernardmauco-create/Incidence)
  branch: main
  base_url: https://sveltia-cms-auth.<SUBDOMAIN>.workers.dev # A RENSEIGNER

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "_posts"
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description SEO", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Archiver", name: "archived", widget: "boolean", default: false, required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "youtube"
    label: "YouTube"
    editor:
      preview: false
    files:
      - label: "Vidéos à la une"
        name: "videos"
        file: "_data/youtube.yml"
        fields:
          - label: "Vidéos"
            name: "videos"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "ID YouTube", name: "id", widget: "string", hint: "Ex: dQw4w9WgXcQ" }
              - { label: "Description", name: "description", widget: "text" }
